// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FavoriteServersColumns holds the columns for the "favorite_servers" table.
	FavoriteServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "addr", Type: field.TypeString, Unique: true},
		{Name: "desc", Type: field.TypeString, Nullable: true},
		{Name: "last_query_time", Type: field.TypeTime, Nullable: true},
		{Name: "rank", Type: field.TypeInt, Default: 7},
	}
	// FavoriteServersTable holds the schema information for the "favorite_servers" table.
	FavoriteServersTable = &schema.Table{
		Name:       "favorite_servers",
		Columns:    FavoriteServersColumns,
		PrimaryKey: []*schema.Column{FavoriteServersColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "rank", Type: field.TypeInt},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// TagServersColumns holds the columns for the "tag_servers" table.
	TagServersColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "favorite_server_id", Type: field.TypeInt},
	}
	// TagServersTable holds the schema information for the "tag_servers" table.
	TagServersTable = &schema.Table{
		Name:       "tag_servers",
		Columns:    TagServersColumns,
		PrimaryKey: []*schema.Column{TagServersColumns[0], TagServersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_servers_tag_id",
				Columns:    []*schema.Column{TagServersColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_servers_favorite_server_id",
				Columns:    []*schema.Column{TagServersColumns[1]},
				RefColumns: []*schema.Column{FavoriteServersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FavoriteServersTable,
		TagsTable,
		TagServersTable,
	}
)

func init() {
	TagServersTable.ForeignKeys[0].RefTable = TagsTable
	TagServersTable.ForeignKeys[1].RefTable = FavoriteServersTable
}
