// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"l4d2serverquery-go/ent/favoriteserver"
	"l4d2serverquery-go/ent/predicate"
	"l4d2serverquery-go/ent/tag"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FavoriteServerQuery is the builder for querying FavoriteServer entities.
type FavoriteServerQuery struct {
	config
	ctx        *QueryContext
	order      []favoriteserver.OrderOption
	inters     []Interceptor
	predicates []predicate.FavoriteServer
	withTags   *TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FavoriteServerQuery builder.
func (fsq *FavoriteServerQuery) Where(ps ...predicate.FavoriteServer) *FavoriteServerQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit the number of records to be returned by this query.
func (fsq *FavoriteServerQuery) Limit(limit int) *FavoriteServerQuery {
	fsq.ctx.Limit = &limit
	return fsq
}

// Offset to start from.
func (fsq *FavoriteServerQuery) Offset(offset int) *FavoriteServerQuery {
	fsq.ctx.Offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FavoriteServerQuery) Unique(unique bool) *FavoriteServerQuery {
	fsq.ctx.Unique = &unique
	return fsq
}

// Order specifies how the records should be ordered.
func (fsq *FavoriteServerQuery) Order(o ...favoriteserver.OrderOption) *FavoriteServerQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// QueryTags chains the current query on the "tags" edge.
func (fsq *FavoriteServerQuery) QueryTags() *TagQuery {
	query := (&TagClient{config: fsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(favoriteserver.Table, favoriteserver.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, favoriteserver.TagsTable, favoriteserver.TagsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(fsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FavoriteServer entity from the query.
// Returns a *NotFoundError when no FavoriteServer was found.
func (fsq *FavoriteServerQuery) First(ctx context.Context) (*FavoriteServer, error) {
	nodes, err := fsq.Limit(1).All(setContextOp(ctx, fsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{favoriteserver.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FavoriteServerQuery) FirstX(ctx context.Context) *FavoriteServer {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FavoriteServer ID from the query.
// Returns a *NotFoundError when no FavoriteServer ID was found.
func (fsq *FavoriteServerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(1).IDs(setContextOp(ctx, fsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{favoriteserver.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FavoriteServerQuery) FirstIDX(ctx context.Context) int {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FavoriteServer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FavoriteServer entity is found.
// Returns a *NotFoundError when no FavoriteServer entities are found.
func (fsq *FavoriteServerQuery) Only(ctx context.Context) (*FavoriteServer, error) {
	nodes, err := fsq.Limit(2).All(setContextOp(ctx, fsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{favoriteserver.Label}
	default:
		return nil, &NotSingularError{favoriteserver.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FavoriteServerQuery) OnlyX(ctx context.Context) *FavoriteServer {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FavoriteServer ID in the query.
// Returns a *NotSingularError when more than one FavoriteServer ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FavoriteServerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(2).IDs(setContextOp(ctx, fsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{favoriteserver.Label}
	default:
		err = &NotSingularError{favoriteserver.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FavoriteServerQuery) OnlyIDX(ctx context.Context) int {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FavoriteServers.
func (fsq *FavoriteServerQuery) All(ctx context.Context) ([]*FavoriteServer, error) {
	ctx = setContextOp(ctx, fsq.ctx, ent.OpQueryAll)
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FavoriteServer, *FavoriteServerQuery]()
	return withInterceptors[[]*FavoriteServer](ctx, fsq, qr, fsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FavoriteServerQuery) AllX(ctx context.Context) []*FavoriteServer {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FavoriteServer IDs.
func (fsq *FavoriteServerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fsq.ctx.Unique == nil && fsq.path != nil {
		fsq.Unique(true)
	}
	ctx = setContextOp(ctx, fsq.ctx, ent.OpQueryIDs)
	if err = fsq.Select(favoriteserver.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FavoriteServerQuery) IDsX(ctx context.Context) []int {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FavoriteServerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fsq.ctx, ent.OpQueryCount)
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fsq, querierCount[*FavoriteServerQuery](), fsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FavoriteServerQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FavoriteServerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fsq.ctx, ent.OpQueryExist)
	switch _, err := fsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FavoriteServerQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FavoriteServerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FavoriteServerQuery) Clone() *FavoriteServerQuery {
	if fsq == nil {
		return nil
	}
	return &FavoriteServerQuery{
		config:     fsq.config,
		ctx:        fsq.ctx.Clone(),
		order:      append([]favoriteserver.OrderOption{}, fsq.order...),
		inters:     append([]Interceptor{}, fsq.inters...),
		predicates: append([]predicate.FavoriteServer{}, fsq.predicates...),
		withTags:   fsq.withTags.Clone(),
		// clone intermediate query.
		sql:  fsq.sql.Clone(),
		path: fsq.path,
	}
}

// WithTags tells the query-builder to eager-load the nodes that are connected to
// the "tags" edge. The optional arguments are used to configure the query builder of the edge.
func (fsq *FavoriteServerQuery) WithTags(opts ...func(*TagQuery)) *FavoriteServerQuery {
	query := (&TagClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fsq.withTags = query
	return fsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Addr string `json:"addr,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FavoriteServer.Query().
//		GroupBy(favoriteserver.FieldAddr).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fsq *FavoriteServerQuery) GroupBy(field string, fields ...string) *FavoriteServerGroupBy {
	fsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FavoriteServerGroupBy{build: fsq}
	grbuild.flds = &fsq.ctx.Fields
	grbuild.label = favoriteserver.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Addr string `json:"addr,omitempty"`
//	}
//
//	client.FavoriteServer.Query().
//		Select(favoriteserver.FieldAddr).
//		Scan(ctx, &v)
func (fsq *FavoriteServerQuery) Select(fields ...string) *FavoriteServerSelect {
	fsq.ctx.Fields = append(fsq.ctx.Fields, fields...)
	sbuild := &FavoriteServerSelect{FavoriteServerQuery: fsq}
	sbuild.label = favoriteserver.Label
	sbuild.flds, sbuild.scan = &fsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FavoriteServerSelect configured with the given aggregations.
func (fsq *FavoriteServerQuery) Aggregate(fns ...AggregateFunc) *FavoriteServerSelect {
	return fsq.Select().Aggregate(fns...)
}

func (fsq *FavoriteServerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fsq); err != nil {
				return err
			}
		}
	}
	for _, f := range fsq.ctx.Fields {
		if !favoriteserver.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FavoriteServerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FavoriteServer, error) {
	var (
		nodes       = []*FavoriteServer{}
		_spec       = fsq.querySpec()
		loadedTypes = [1]bool{
			fsq.withTags != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FavoriteServer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FavoriteServer{config: fsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fsq.withTags; query != nil {
		if err := fsq.loadTags(ctx, query, nodes,
			func(n *FavoriteServer) { n.Edges.Tags = []*Tag{} },
			func(n *FavoriteServer, e *Tag) { n.Edges.Tags = append(n.Edges.Tags, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fsq *FavoriteServerQuery) loadTags(ctx context.Context, query *TagQuery, nodes []*FavoriteServer, init func(*FavoriteServer), assign func(*FavoriteServer, *Tag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*FavoriteServer)
	nids := make(map[int]map[*FavoriteServer]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(favoriteserver.TagsTable)
		s.Join(joinT).On(s.C(tag.FieldID), joinT.C(favoriteserver.TagsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(favoriteserver.TagsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(favoriteserver.TagsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*FavoriteServer]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Tag](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tags" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (fsq *FavoriteServerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	_spec.Node.Columns = fsq.ctx.Fields
	if len(fsq.ctx.Fields) > 0 {
		_spec.Unique = fsq.ctx.Unique != nil && *fsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FavoriteServerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(favoriteserver.Table, favoriteserver.Columns, sqlgraph.NewFieldSpec(favoriteserver.FieldID, field.TypeInt))
	_spec.From = fsq.sql
	if unique := fsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fsq.path != nil {
		_spec.Unique = true
	}
	if fields := fsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favoriteserver.FieldID)
		for i := range fields {
			if fields[i] != favoriteserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FavoriteServerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(favoriteserver.Table)
	columns := fsq.ctx.Fields
	if len(columns) == 0 {
		columns = favoriteserver.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.ctx.Unique != nil && *fsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FavoriteServerGroupBy is the group-by builder for FavoriteServer entities.
type FavoriteServerGroupBy struct {
	selector
	build *FavoriteServerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FavoriteServerGroupBy) Aggregate(fns ...AggregateFunc) *FavoriteServerGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the selector query and scans the result into the given value.
func (fsgb *FavoriteServerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fsgb.build.ctx, ent.OpQueryGroupBy)
	if err := fsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FavoriteServerQuery, *FavoriteServerGroupBy](ctx, fsgb.build, fsgb, fsgb.build.inters, v)
}

func (fsgb *FavoriteServerGroupBy) sqlScan(ctx context.Context, root *FavoriteServerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fsgb.flds)+len(fsgb.fns))
		for _, f := range *fsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FavoriteServerSelect is the builder for selecting fields of FavoriteServer entities.
type FavoriteServerSelect struct {
	*FavoriteServerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fss *FavoriteServerSelect) Aggregate(fns ...AggregateFunc) *FavoriteServerSelect {
	fss.fns = append(fss.fns, fns...)
	return fss
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FavoriteServerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fss.ctx, ent.OpQuerySelect)
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FavoriteServerQuery, *FavoriteServerSelect](ctx, fss.FavoriteServerQuery, fss, fss.inters, v)
}

func (fss *FavoriteServerSelect) sqlScan(ctx context.Context, root *FavoriteServerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fss.fns))
	for _, fn := range fss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
