// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"l4d2serverquery-go/ent/favoriteserver"
	"l4d2serverquery-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FavoriteServerDelete is the builder for deleting a FavoriteServer entity.
type FavoriteServerDelete struct {
	config
	hooks    []Hook
	mutation *FavoriteServerMutation
}

// Where appends a list predicates to the FavoriteServerDelete builder.
func (fsd *FavoriteServerDelete) Where(ps ...predicate.FavoriteServer) *FavoriteServerDelete {
	fsd.mutation.Where(ps...)
	return fsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fsd *FavoriteServerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fsd.sqlExec, fsd.mutation, fsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fsd *FavoriteServerDelete) ExecX(ctx context.Context) int {
	n, err := fsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fsd *FavoriteServerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(favoriteserver.Table, sqlgraph.NewFieldSpec(favoriteserver.FieldID, field.TypeInt))
	if ps := fsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fsd.mutation.done = true
	return affected, err
}

// FavoriteServerDeleteOne is the builder for deleting a single FavoriteServer entity.
type FavoriteServerDeleteOne struct {
	fsd *FavoriteServerDelete
}

// Where appends a list predicates to the FavoriteServerDelete builder.
func (fsdo *FavoriteServerDeleteOne) Where(ps ...predicate.FavoriteServer) *FavoriteServerDeleteOne {
	fsdo.fsd.mutation.Where(ps...)
	return fsdo
}

// Exec executes the deletion query.
func (fsdo *FavoriteServerDeleteOne) Exec(ctx context.Context) error {
	n, err := fsdo.fsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{favoriteserver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fsdo *FavoriteServerDeleteOne) ExecX(ctx context.Context) {
	if err := fsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
