// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"l4d2serverquery-go/ent/favoriteserver"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FavoriteServer is the model entity for the FavoriteServer schema.
type FavoriteServer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Addr holds the value of the "addr" field.
	Addr string `json:"addr,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Desc holds the value of the "desc" field.
	Desc string `json:"desc,omitempty"`
	// LastQueryTime holds the value of the "last_query_time" field.
	LastQueryTime time.Time `json:"last_query_time,omitempty"`
	// Rank holds the value of the "rank" field.
	Rank int `json:"rank,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FavoriteServerQuery when eager-loading is set.
	Edges        FavoriteServerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FavoriteServerEdges holds the relations/edges for other nodes in the graph.
type FavoriteServerEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e FavoriteServerEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FavoriteServer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case favoriteserver.FieldID, favoriteserver.FieldRank:
			values[i] = new(sql.NullInt64)
		case favoriteserver.FieldAddr, favoriteserver.FieldName, favoriteserver.FieldDesc:
			values[i] = new(sql.NullString)
		case favoriteserver.FieldLastQueryTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FavoriteServer fields.
func (_m *FavoriteServer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case favoriteserver.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case favoriteserver.FieldAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field addr", values[i])
			} else if value.Valid {
				_m.Addr = value.String
			}
		case favoriteserver.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case favoriteserver.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				_m.Desc = value.String
			}
		case favoriteserver.FieldLastQueryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_query_time", values[i])
			} else if value.Valid {
				_m.LastQueryTime = value.Time
			}
		case favoriteserver.FieldRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank", values[i])
			} else if value.Valid {
				_m.Rank = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FavoriteServer.
// This includes values selected through modifiers, order, etc.
func (_m *FavoriteServer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTags queries the "tags" edge of the FavoriteServer entity.
func (_m *FavoriteServer) QueryTags() *TagQuery {
	return NewFavoriteServerClient(_m.config).QueryTags(_m)
}

// Update returns a builder for updating this FavoriteServer.
// Note that you need to call FavoriteServer.Unwrap() before calling this method if this FavoriteServer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FavoriteServer) Update() *FavoriteServerUpdateOne {
	return NewFavoriteServerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FavoriteServer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FavoriteServer) Unwrap() *FavoriteServer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FavoriteServer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FavoriteServer) String() string {
	var builder strings.Builder
	builder.WriteString("FavoriteServer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("addr=")
	builder.WriteString(_m.Addr)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("desc=")
	builder.WriteString(_m.Desc)
	builder.WriteString(", ")
	builder.WriteString("last_query_time=")
	builder.WriteString(_m.LastQueryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rank=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rank))
	builder.WriteByte(')')
	return builder.String()
}

// FavoriteServers is a parsable slice of FavoriteServer.
type FavoriteServers []*FavoriteServer
