// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"l4d2serverquery-go/ent/favoriteserver"
	"l4d2serverquery-go/ent/predicate"
	"l4d2serverquery-go/ent/tag"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FavoriteServerUpdate is the builder for updating FavoriteServer entities.
type FavoriteServerUpdate struct {
	config
	hooks    []Hook
	mutation *FavoriteServerMutation
}

// Where appends a list predicates to the FavoriteServerUpdate builder.
func (fsu *FavoriteServerUpdate) Where(ps ...predicate.FavoriteServer) *FavoriteServerUpdate {
	fsu.mutation.Where(ps...)
	return fsu
}

// SetAddr sets the "addr" field.
func (fsu *FavoriteServerUpdate) SetAddr(s string) *FavoriteServerUpdate {
	fsu.mutation.SetAddr(s)
	return fsu
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (fsu *FavoriteServerUpdate) SetNillableAddr(s *string) *FavoriteServerUpdate {
	if s != nil {
		fsu.SetAddr(*s)
	}
	return fsu
}

// SetName sets the "name" field.
func (fsu *FavoriteServerUpdate) SetName(s string) *FavoriteServerUpdate {
	fsu.mutation.SetName(s)
	return fsu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (fsu *FavoriteServerUpdate) SetNillableName(s *string) *FavoriteServerUpdate {
	if s != nil {
		fsu.SetName(*s)
	}
	return fsu
}

// ClearName clears the value of the "name" field.
func (fsu *FavoriteServerUpdate) ClearName() *FavoriteServerUpdate {
	fsu.mutation.ClearName()
	return fsu
}

// SetDesc sets the "desc" field.
func (fsu *FavoriteServerUpdate) SetDesc(s string) *FavoriteServerUpdate {
	fsu.mutation.SetDesc(s)
	return fsu
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (fsu *FavoriteServerUpdate) SetNillableDesc(s *string) *FavoriteServerUpdate {
	if s != nil {
		fsu.SetDesc(*s)
	}
	return fsu
}

// ClearDesc clears the value of the "desc" field.
func (fsu *FavoriteServerUpdate) ClearDesc() *FavoriteServerUpdate {
	fsu.mutation.ClearDesc()
	return fsu
}

// SetLastQueryTime sets the "last_query_time" field.
func (fsu *FavoriteServerUpdate) SetLastQueryTime(t time.Time) *FavoriteServerUpdate {
	fsu.mutation.SetLastQueryTime(t)
	return fsu
}

// SetNillableLastQueryTime sets the "last_query_time" field if the given value is not nil.
func (fsu *FavoriteServerUpdate) SetNillableLastQueryTime(t *time.Time) *FavoriteServerUpdate {
	if t != nil {
		fsu.SetLastQueryTime(*t)
	}
	return fsu
}

// ClearLastQueryTime clears the value of the "last_query_time" field.
func (fsu *FavoriteServerUpdate) ClearLastQueryTime() *FavoriteServerUpdate {
	fsu.mutation.ClearLastQueryTime()
	return fsu
}

// SetRank sets the "rank" field.
func (fsu *FavoriteServerUpdate) SetRank(i int) *FavoriteServerUpdate {
	fsu.mutation.ResetRank()
	fsu.mutation.SetRank(i)
	return fsu
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (fsu *FavoriteServerUpdate) SetNillableRank(i *int) *FavoriteServerUpdate {
	if i != nil {
		fsu.SetRank(*i)
	}
	return fsu
}

// AddRank adds i to the "rank" field.
func (fsu *FavoriteServerUpdate) AddRank(i int) *FavoriteServerUpdate {
	fsu.mutation.AddRank(i)
	return fsu
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (fsu *FavoriteServerUpdate) AddTagIDs(ids ...int) *FavoriteServerUpdate {
	fsu.mutation.AddTagIDs(ids...)
	return fsu
}

// AddTags adds the "tags" edges to the Tag entity.
func (fsu *FavoriteServerUpdate) AddTags(t ...*Tag) *FavoriteServerUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fsu.AddTagIDs(ids...)
}

// Mutation returns the FavoriteServerMutation object of the builder.
func (fsu *FavoriteServerUpdate) Mutation() *FavoriteServerMutation {
	return fsu.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (fsu *FavoriteServerUpdate) ClearTags() *FavoriteServerUpdate {
	fsu.mutation.ClearTags()
	return fsu
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (fsu *FavoriteServerUpdate) RemoveTagIDs(ids ...int) *FavoriteServerUpdate {
	fsu.mutation.RemoveTagIDs(ids...)
	return fsu
}

// RemoveTags removes "tags" edges to Tag entities.
func (fsu *FavoriteServerUpdate) RemoveTags(t ...*Tag) *FavoriteServerUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fsu.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fsu *FavoriteServerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fsu.sqlSave, fsu.mutation, fsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsu *FavoriteServerUpdate) SaveX(ctx context.Context) int {
	affected, err := fsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fsu *FavoriteServerUpdate) Exec(ctx context.Context) error {
	_, err := fsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsu *FavoriteServerUpdate) ExecX(ctx context.Context) {
	if err := fsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsu *FavoriteServerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(favoriteserver.Table, favoriteserver.Columns, sqlgraph.NewFieldSpec(favoriteserver.FieldID, field.TypeInt))
	if ps := fsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsu.mutation.Addr(); ok {
		_spec.SetField(favoriteserver.FieldAddr, field.TypeString, value)
	}
	if value, ok := fsu.mutation.Name(); ok {
		_spec.SetField(favoriteserver.FieldName, field.TypeString, value)
	}
	if fsu.mutation.NameCleared() {
		_spec.ClearField(favoriteserver.FieldName, field.TypeString)
	}
	if value, ok := fsu.mutation.Desc(); ok {
		_spec.SetField(favoriteserver.FieldDesc, field.TypeString, value)
	}
	if fsu.mutation.DescCleared() {
		_spec.ClearField(favoriteserver.FieldDesc, field.TypeString)
	}
	if value, ok := fsu.mutation.LastQueryTime(); ok {
		_spec.SetField(favoriteserver.FieldLastQueryTime, field.TypeTime, value)
	}
	if fsu.mutation.LastQueryTimeCleared() {
		_spec.ClearField(favoriteserver.FieldLastQueryTime, field.TypeTime)
	}
	if value, ok := fsu.mutation.Rank(); ok {
		_spec.SetField(favoriteserver.FieldRank, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedRank(); ok {
		_spec.AddField(favoriteserver.FieldRank, field.TypeInt, value)
	}
	if fsu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !fsu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favoriteserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fsu.mutation.done = true
	return n, nil
}

// FavoriteServerUpdateOne is the builder for updating a single FavoriteServer entity.
type FavoriteServerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavoriteServerMutation
}

// SetAddr sets the "addr" field.
func (fsuo *FavoriteServerUpdateOne) SetAddr(s string) *FavoriteServerUpdateOne {
	fsuo.mutation.SetAddr(s)
	return fsuo
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (fsuo *FavoriteServerUpdateOne) SetNillableAddr(s *string) *FavoriteServerUpdateOne {
	if s != nil {
		fsuo.SetAddr(*s)
	}
	return fsuo
}

// SetName sets the "name" field.
func (fsuo *FavoriteServerUpdateOne) SetName(s string) *FavoriteServerUpdateOne {
	fsuo.mutation.SetName(s)
	return fsuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (fsuo *FavoriteServerUpdateOne) SetNillableName(s *string) *FavoriteServerUpdateOne {
	if s != nil {
		fsuo.SetName(*s)
	}
	return fsuo
}

// ClearName clears the value of the "name" field.
func (fsuo *FavoriteServerUpdateOne) ClearName() *FavoriteServerUpdateOne {
	fsuo.mutation.ClearName()
	return fsuo
}

// SetDesc sets the "desc" field.
func (fsuo *FavoriteServerUpdateOne) SetDesc(s string) *FavoriteServerUpdateOne {
	fsuo.mutation.SetDesc(s)
	return fsuo
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (fsuo *FavoriteServerUpdateOne) SetNillableDesc(s *string) *FavoriteServerUpdateOne {
	if s != nil {
		fsuo.SetDesc(*s)
	}
	return fsuo
}

// ClearDesc clears the value of the "desc" field.
func (fsuo *FavoriteServerUpdateOne) ClearDesc() *FavoriteServerUpdateOne {
	fsuo.mutation.ClearDesc()
	return fsuo
}

// SetLastQueryTime sets the "last_query_time" field.
func (fsuo *FavoriteServerUpdateOne) SetLastQueryTime(t time.Time) *FavoriteServerUpdateOne {
	fsuo.mutation.SetLastQueryTime(t)
	return fsuo
}

// SetNillableLastQueryTime sets the "last_query_time" field if the given value is not nil.
func (fsuo *FavoriteServerUpdateOne) SetNillableLastQueryTime(t *time.Time) *FavoriteServerUpdateOne {
	if t != nil {
		fsuo.SetLastQueryTime(*t)
	}
	return fsuo
}

// ClearLastQueryTime clears the value of the "last_query_time" field.
func (fsuo *FavoriteServerUpdateOne) ClearLastQueryTime() *FavoriteServerUpdateOne {
	fsuo.mutation.ClearLastQueryTime()
	return fsuo
}

// SetRank sets the "rank" field.
func (fsuo *FavoriteServerUpdateOne) SetRank(i int) *FavoriteServerUpdateOne {
	fsuo.mutation.ResetRank()
	fsuo.mutation.SetRank(i)
	return fsuo
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (fsuo *FavoriteServerUpdateOne) SetNillableRank(i *int) *FavoriteServerUpdateOne {
	if i != nil {
		fsuo.SetRank(*i)
	}
	return fsuo
}

// AddRank adds i to the "rank" field.
func (fsuo *FavoriteServerUpdateOne) AddRank(i int) *FavoriteServerUpdateOne {
	fsuo.mutation.AddRank(i)
	return fsuo
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (fsuo *FavoriteServerUpdateOne) AddTagIDs(ids ...int) *FavoriteServerUpdateOne {
	fsuo.mutation.AddTagIDs(ids...)
	return fsuo
}

// AddTags adds the "tags" edges to the Tag entity.
func (fsuo *FavoriteServerUpdateOne) AddTags(t ...*Tag) *FavoriteServerUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fsuo.AddTagIDs(ids...)
}

// Mutation returns the FavoriteServerMutation object of the builder.
func (fsuo *FavoriteServerUpdateOne) Mutation() *FavoriteServerMutation {
	return fsuo.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (fsuo *FavoriteServerUpdateOne) ClearTags() *FavoriteServerUpdateOne {
	fsuo.mutation.ClearTags()
	return fsuo
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (fsuo *FavoriteServerUpdateOne) RemoveTagIDs(ids ...int) *FavoriteServerUpdateOne {
	fsuo.mutation.RemoveTagIDs(ids...)
	return fsuo
}

// RemoveTags removes "tags" edges to Tag entities.
func (fsuo *FavoriteServerUpdateOne) RemoveTags(t ...*Tag) *FavoriteServerUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fsuo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the FavoriteServerUpdate builder.
func (fsuo *FavoriteServerUpdateOne) Where(ps ...predicate.FavoriteServer) *FavoriteServerUpdateOne {
	fsuo.mutation.Where(ps...)
	return fsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fsuo *FavoriteServerUpdateOne) Select(field string, fields ...string) *FavoriteServerUpdateOne {
	fsuo.fields = append([]string{field}, fields...)
	return fsuo
}

// Save executes the query and returns the updated FavoriteServer entity.
func (fsuo *FavoriteServerUpdateOne) Save(ctx context.Context) (*FavoriteServer, error) {
	return withHooks(ctx, fsuo.sqlSave, fsuo.mutation, fsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsuo *FavoriteServerUpdateOne) SaveX(ctx context.Context) *FavoriteServer {
	node, err := fsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fsuo *FavoriteServerUpdateOne) Exec(ctx context.Context) error {
	_, err := fsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsuo *FavoriteServerUpdateOne) ExecX(ctx context.Context) {
	if err := fsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsuo *FavoriteServerUpdateOne) sqlSave(ctx context.Context) (_node *FavoriteServer, err error) {
	_spec := sqlgraph.NewUpdateSpec(favoriteserver.Table, favoriteserver.Columns, sqlgraph.NewFieldSpec(favoriteserver.FieldID, field.TypeInt))
	id, ok := fsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FavoriteServer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favoriteserver.FieldID)
		for _, f := range fields {
			if !favoriteserver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favoriteserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsuo.mutation.Addr(); ok {
		_spec.SetField(favoriteserver.FieldAddr, field.TypeString, value)
	}
	if value, ok := fsuo.mutation.Name(); ok {
		_spec.SetField(favoriteserver.FieldName, field.TypeString, value)
	}
	if fsuo.mutation.NameCleared() {
		_spec.ClearField(favoriteserver.FieldName, field.TypeString)
	}
	if value, ok := fsuo.mutation.Desc(); ok {
		_spec.SetField(favoriteserver.FieldDesc, field.TypeString, value)
	}
	if fsuo.mutation.DescCleared() {
		_spec.ClearField(favoriteserver.FieldDesc, field.TypeString)
	}
	if value, ok := fsuo.mutation.LastQueryTime(); ok {
		_spec.SetField(favoriteserver.FieldLastQueryTime, field.TypeTime, value)
	}
	if fsuo.mutation.LastQueryTimeCleared() {
		_spec.ClearField(favoriteserver.FieldLastQueryTime, field.TypeTime)
	}
	if value, ok := fsuo.mutation.Rank(); ok {
		_spec.SetField(favoriteserver.FieldRank, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedRank(); ok {
		_spec.AddField(favoriteserver.FieldRank, field.TypeInt, value)
	}
	if fsuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsuo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !fsuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsuo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FavoriteServer{config: fsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favoriteserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fsuo.mutation.done = true
	return _node, nil
}
