// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"l4d2serverquery-go/ent/favoriteserver"
	"l4d2serverquery-go/ent/tag"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FavoriteServerCreate is the builder for creating a FavoriteServer entity.
type FavoriteServerCreate struct {
	config
	mutation *FavoriteServerMutation
	hooks    []Hook
}

// SetAddr sets the "addr" field.
func (fsc *FavoriteServerCreate) SetAddr(s string) *FavoriteServerCreate {
	fsc.mutation.SetAddr(s)
	return fsc
}

// SetDesc sets the "desc" field.
func (fsc *FavoriteServerCreate) SetDesc(s string) *FavoriteServerCreate {
	fsc.mutation.SetDesc(s)
	return fsc
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (fsc *FavoriteServerCreate) SetNillableDesc(s *string) *FavoriteServerCreate {
	if s != nil {
		fsc.SetDesc(*s)
	}
	return fsc
}

// SetLastQueryTime sets the "last_query_time" field.
func (fsc *FavoriteServerCreate) SetLastQueryTime(t time.Time) *FavoriteServerCreate {
	fsc.mutation.SetLastQueryTime(t)
	return fsc
}

// SetNillableLastQueryTime sets the "last_query_time" field if the given value is not nil.
func (fsc *FavoriteServerCreate) SetNillableLastQueryTime(t *time.Time) *FavoriteServerCreate {
	if t != nil {
		fsc.SetLastQueryTime(*t)
	}
	return fsc
}

// SetRank sets the "rank" field.
func (fsc *FavoriteServerCreate) SetRank(i int) *FavoriteServerCreate {
	fsc.mutation.SetRank(i)
	return fsc
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (fsc *FavoriteServerCreate) SetNillableRank(i *int) *FavoriteServerCreate {
	if i != nil {
		fsc.SetRank(*i)
	}
	return fsc
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (fsc *FavoriteServerCreate) AddTagIDs(ids ...int) *FavoriteServerCreate {
	fsc.mutation.AddTagIDs(ids...)
	return fsc
}

// AddTags adds the "tags" edges to the Tag entity.
func (fsc *FavoriteServerCreate) AddTags(t ...*Tag) *FavoriteServerCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fsc.AddTagIDs(ids...)
}

// Mutation returns the FavoriteServerMutation object of the builder.
func (fsc *FavoriteServerCreate) Mutation() *FavoriteServerMutation {
	return fsc.mutation
}

// Save creates the FavoriteServer in the database.
func (fsc *FavoriteServerCreate) Save(ctx context.Context) (*FavoriteServer, error) {
	fsc.defaults()
	return withHooks(ctx, fsc.sqlSave, fsc.mutation, fsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fsc *FavoriteServerCreate) SaveX(ctx context.Context) *FavoriteServer {
	v, err := fsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fsc *FavoriteServerCreate) Exec(ctx context.Context) error {
	_, err := fsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsc *FavoriteServerCreate) ExecX(ctx context.Context) {
	if err := fsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fsc *FavoriteServerCreate) defaults() {
	if _, ok := fsc.mutation.Rank(); !ok {
		v := favoriteserver.DefaultRank
		fsc.mutation.SetRank(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fsc *FavoriteServerCreate) check() error {
	if _, ok := fsc.mutation.Addr(); !ok {
		return &ValidationError{Name: "addr", err: errors.New(`ent: missing required field "FavoriteServer.addr"`)}
	}
	if _, ok := fsc.mutation.Rank(); !ok {
		return &ValidationError{Name: "rank", err: errors.New(`ent: missing required field "FavoriteServer.rank"`)}
	}
	return nil
}

func (fsc *FavoriteServerCreate) sqlSave(ctx context.Context) (*FavoriteServer, error) {
	if err := fsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fsc.mutation.id = &_node.ID
	fsc.mutation.done = true
	return _node, nil
}

func (fsc *FavoriteServerCreate) createSpec() (*FavoriteServer, *sqlgraph.CreateSpec) {
	var (
		_node = &FavoriteServer{config: fsc.config}
		_spec = sqlgraph.NewCreateSpec(favoriteserver.Table, sqlgraph.NewFieldSpec(favoriteserver.FieldID, field.TypeInt))
	)
	if value, ok := fsc.mutation.Addr(); ok {
		_spec.SetField(favoriteserver.FieldAddr, field.TypeString, value)
		_node.Addr = value
	}
	if value, ok := fsc.mutation.Desc(); ok {
		_spec.SetField(favoriteserver.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := fsc.mutation.LastQueryTime(); ok {
		_spec.SetField(favoriteserver.FieldLastQueryTime, field.TypeTime, value)
		_node.LastQueryTime = value
	}
	if value, ok := fsc.mutation.Rank(); ok {
		_spec.SetField(favoriteserver.FieldRank, field.TypeInt, value)
		_node.Rank = value
	}
	if nodes := fsc.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   favoriteserver.TagsTable,
			Columns: favoriteserver.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FavoriteServerCreateBulk is the builder for creating many FavoriteServer entities in bulk.
type FavoriteServerCreateBulk struct {
	config
	err      error
	builders []*FavoriteServerCreate
}

// Save creates the FavoriteServer entities in the database.
func (fscb *FavoriteServerCreateBulk) Save(ctx context.Context) ([]*FavoriteServer, error) {
	if fscb.err != nil {
		return nil, fscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fscb.builders))
	nodes := make([]*FavoriteServer, len(fscb.builders))
	mutators := make([]Mutator, len(fscb.builders))
	for i := range fscb.builders {
		func(i int, root context.Context) {
			builder := fscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FavoriteServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fscb *FavoriteServerCreateBulk) SaveX(ctx context.Context) []*FavoriteServer {
	v, err := fscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fscb *FavoriteServerCreateBulk) Exec(ctx context.Context) error {
	_, err := fscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fscb *FavoriteServerCreateBulk) ExecX(ctx context.Context) {
	if err := fscb.Exec(ctx); err != nil {
		panic(err)
	}
}
