// Code generated by ent, DO NOT EDIT.

package ent

import (
	"l4d2serverquery-go/ent/favoriteserver"
	"l4d2serverquery-go/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	favoriteserverFields := schema.FavoriteServer{}.Fields()
	_ = favoriteserverFields
	// favoriteserverDescRank is the schema descriptor for rank field.
	favoriteserverDescRank := favoriteserverFields[3].Descriptor()
	// favoriteserver.DefaultRank holds the default value on creation for the rank field.
	favoriteserver.DefaultRank = favoriteserverDescRank.Default.(int)
}
