// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FavoriteServer is the predicate function for favoriteserver builders.
type FavoriteServer func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
